import { NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';

export const dynamic = 'force-dynamic';

export async function GET() {
  const now = new Date();
  const todayStart = new Date(now.getFullYear(), now.getMonth(), now.getDate()).toISOString();

  try {
    // Fetch all history for detailed analytics
    const { data: allHistory, error: he } = await supabase
      .from('district_history')
      .select('*');

    if (he) throw new Error('Analytics query failed');

    const active = allHistory?.filter(h => !h.end_time) || [];
    const resolvedToday = allHistory?.filter(h => h.end_time && h.end_time >= todayStart) || [];
    const allResolved = allHistory?.filter(h => h.end_time) || [];

    const activeOutagesCount = active.length;
    const resolvedTodayCount = resolvedToday.length;

    let totalMinutes = 0;
    allResolved.forEach(o => {
      const duration = new Date(o.end_time).getTime() - new Date(o.start_time).getTime();
      totalMinutes += duration / 60000;
    });

    const averageRestorationMinutes = allResolved.length ? totalMinutes / allResolved.length : 120;
    const gridReliability = Math.max(0, 100 - (activeOutagesCount * 0.5));

    // outagesByArea
    const outagesByArea = allHistory?.reduce((acc: Record<string, number>, curr) => {
      const area = curr.district || curr.area || 'Unknown';
      acc[area] = (acc[area] || 0) + 1;
      return acc;
    }, {}) || {};

    // outagesBySeverity
    const outagesBySeverity = allHistory?.reduce((acc: any, curr) => {
      const sev = curr.severity || 'moderate';
      acc[sev] = (acc[sev] || 0) + 1;
      return acc;
    }, { low: 0, moderate: 0, critical: 0, grid_failure: 0 });

    // Mock Time Series Data (since we might not have enough historical distribution in the DB yet)
    // In a production app, these would be generated by SQL aggregations (GROUP BY date)
    const hourlyData = Array.from({ length: 24 }).map((_, i) => ({
      hour: `${i}:00`,
      count: allHistory?.filter(h => new Date(h.start_time).getHours() === i).length || 0
    }));

    const dailyData = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map((day, i) => ({
      day,
      count: allHistory?.filter(h => new Date(h.start_time).getDay() === i).length || 0
    }));

    const weeklyData = Array.from({ length: 4 }).map((_, i) => ({
      week: `Week ${i + 1}`,
      count: Math.floor((allHistory?.length || 0) / (4 - i)) || 0
    }));

    const monthlyData = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'].map((month, i) => ({
      month,
      count: allHistory?.filter(h => new Date(h.start_time).getMonth() === i).length || 0
    }));

    return NextResponse.json({
      totalOutages: allHistory?.length || 0,
      activeOutages: activeOutagesCount,
      resolvedToday: resolvedTodayCount,
      gridReliability,
      averageRestorationMinutes,
      outagesByArea,
      outagesBySeverity,
      hourlyData,
      dailyData,
      weeklyData,
      monthlyData
    });
  } catch (err) {
    console.error('Analytics Error:', err);
    return NextResponse.json({
      totalOutages: 0,
      activeOutages: 0,
      resolvedToday: 0,
      gridReliability: 100,
      averageRestorationMinutes: 0,
      outagesByArea: {},
      outagesBySeverity: { low: 0, moderate: 0, critical: 0, grid_failure: 0 },
      hourlyData: [],
      dailyData: [],
      weeklyData: [],
      monthlyData: []
    });
  }
}
